name: axc_permission
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: club.axclogo.flutter.axc_permission
        pluginClass: AxcPermissionPlugin
      ios:
        pluginClass: AxcPermissionPlugin